### ISSUE TITLE
Distance tool doesn't seem to work for me.  The overlay is just 5 cars on default settings

### ISSUE THREAD

**Issue by npuldon** [dewiniaid/RailTools#1]
Looks like it should be 6 cars with default settings I believe.

**Comment by dewiniaid** [comment]
RailTools doesn't add additional train ghosts (I wish!  Maybe in the distant future).

It just shows text showing the distance between signals, with the number of train cars in parenthesis.  Is that functionality working for you?

**Comment by npuldon** [comment]
yes, that is working.  I'm trying to understand the different ways the mod can be useful.  Perhaps I'm over hyping it.  Is the order of operations, place a rail signal after a branch or merge, press \ on that rail signal, place a train stop right before the next signal if you want those rails to be a train stop, else end the operation?

Is that all there is to it?

**Comment by dewiniaid** [comment]
The distance display gives you distance between signals.  The relevant part is mostly ensuring that you have enough room after a junction for your train to fit, so if it has to stop it won't have the tail end sticking in the junction and thus potentially contributing a deadlock.  It also is useful for constructs like making a dedicated turning lane that can pull one train off the mainline where it doesn't slow down traffic behind it while it waits to turn.  Version 0.1.1 also shows the nearest signal in either direction -- handy if dealing with very long trains with a signal offscreen.  Lastly, there's the warnings of potentially problematic signals.

The rest of it is mostly: Backslash creates an area that's deadlock-free (assuming you don't have other signals that muck with it) so you don't have to measure out the space yourself.  Shift-backslash automatically adds signals periodically along the entire line -- and these can be shorter than your train distance (to allow trains to follow each other more closely).

What RailTools does in terms of features is pretty simple -- the only reason nobody's done it before is because actually working with rails in the current API is quite difficult.
